# Week 8A: Web scraping

Learn to inspect a webpage, select HTML elements, and organize scraped records in a DataFrame.

**Lecture guide:** Why scrape? → Responsible scraping → Web fundamentals → Browser inspection → Guided demo

## Course roadmap

Moving in to our "getting data" modules

- Today: web scraping
- Next week: APIs, Census data, natural language processing
- Then: vibe coding for website development, GitHub page hosting, machine learning

The final project will ask you to combine several of these topics/techniques to analyze a data sets and produce a web-based data visualization

## Week 8A agenda: web scraping

- Why web scraping? 
- Getting familiar with the Web
- Web scraping: extracting data from static sites
- How to deal with dynamic content

## Part 1: Why scrape the web?

### What is web scraping?

Using software to gather and extract data/content from websites

### Why is web scraping useful?

- Not every data source provides an API
- The Web contains **a lot** of information
- Unique data sources that may not be available elsewhere

### Example: 11 million Craigslist rental listings

<center>
<img src="imgs/scraping-craigslist.jpeg" width=700></img>
</center>

[Source: Geoff Boeing](https://geoffboeing.com/2016/08/craigslist-rental-housing-insights/)

### Challenges of web scraping

- It can be time consuming and difficult to extract large volumes 
- You are at the mercy of website maintainers — if the website structure changes, your code breaks
- Most importantly, there are ethical and legal concerns

<center>
    <img src="imgs/google-search.png" width=700></img>
</center>

## Part 2: Responsible scraping

### Legal concerns

RadPad scraped the entirety of Craiglist, Craigslist sued RadPad, and they were [awarded $60 million](http://labusinessjournal.com/news/2017/apr/14/radpad-ordered-pay-605-million-judgment-craigslist/)

<center>
<img src="imgs/radpad.png" width=500></img>
</center>

### Two types of legal issues

1. Copyright infringement
    - For example: pictures, rental listing text
2. Terms of Use violations
    - **Unauthorized**: Is scraping prohibited in the website’s terms of use?
    - **Intentional**: Was the person aware of the terms? Did they check an “I agree to these terms” box?
    - **Causes damage**: Did the scraping overload the website, blocking user access?

### Public-site scraping: the LinkedIn case

- Ruling from 2022 said that scraping data that is publicly accessible on the internet is not a violation of the Computer Fraud and Abuse Act
- Linkedin had sued a competitor for scraping publicly available information from user profiles

[More info on the case](https://techcrunch.com/2022/04/18/web-scraping-legal-court/)

### Problematic use cases

- The facial recognition startup Clearview AI scraped billions of photos from social media websites. They [recently settled](https://www.mediapost.com/publications/article/389525/facial-recognition-company-clearview-settles-priva.html) a class action lawsuit that alleged they violated privacy laws
- Web scraping at a massive scale has been a key ingredient in generating the training datasets for generative AI models like ChatGPT. Companies like OpenAI and Meta [have been sued](https://apnews.com/article/openai-lawsuit-authors-grisham-george-rr-martin-37f9073ab67ab25b7e6b2975b2a63bfe) by authors and other content creators for violating copyright laws.

### When is scraping more likely to be appropriate?

- .gov sites and, to a lesser degree, .edu sites
- Website owner has no business reason to protect the information
- Not prohibited in terms of use
- Limited number of requests
- Not too many requests all at once
- Done at night, when web traffic is low

### When is scraping less likely to be appropriate?

- search engines
- E-commerce sites (e.g. Zillow, Expedia, Amazon)
- Social media
- Prohibited in terms of use
- Large number of requests
- High frequency of requests

**With that being said, let's do some web scraping...**

## Part 3: Web fundamentals

So many acronyms:

- HTML
- The DOM
- CSS

### HTML: HyperText Markup Language

- The language most websites are written in
- The browser knows how to read this language and renders the output for you
- HTML is what a web crawler will see

#### HTML tags

- There are a standard set of tags to define the different structural components of a webpage
- For example: 
    - `<h1>`, `<h2>` tags define headers
    - `<p>` tags define paragraphs
    - `<ol>` and `<ul>` are ordered and unordered lists

#### Rendering HTML in Jupyter

Use the `%%html` magic cell command

In [15]:
%%html

<html>
  <head>
    <title>TITLE GOES HERE</title>
  </head>
  <body>
    <h3>MAIN CONTENT GOES IN THE BODY TAG</h3>
    <p>This is a paragraph tag</p>
    <p>This is a second paragraph tag</p>
  </body>
</html>

#### Elements, tags, and attributes

Learning the notation:

In [16]:
%%html

<a id="my-link" style="color: orange;" href="https://www.design.upenn.edu" target="blank_">This is my link</a>

**The element:** ![](imgs/atag-1.png)

**The tag:**
![](imgs/atag-2.png)

**The attributes:**

![](imgs/atag-3.png)

#### Special attributes: id and class

- In particular: `id` and `class`
- Allows you to: 
    - select and manipulate specific elements
    - apply styling to specific types of elements

### CSS: Cascading Style Sheets

- A language for styling HTML pages
- CSS styles (also known as selectors) are applied to HTML tags based on their name, class, or ID.

<center>
    <img src="imgs/css.png" width="1200"></img>
</center>

#### Basic CSS selectors

- Class
    - e.g., `.red`
- ID
    - e.g., `#some-id`
- Tag
    - e.g., `p`, `li`, `div`

- **IDs:** unique identifiers
    - no two elements on a page will have the same ID.
- **Classes:** not unique
    - many elements will have the same class
    - a single element can have multiple classes
    
And many more: look up the syntax when you need it

[https://www.w3schools.com/cssref/css_selectors.asp](https://www.w3schools.com/cssref/css_selectors.asp)

### The DOM: Document Object Model

- An interactive object tree created from the HTML tag hierarchy on a page
- Created by the browser
- Tracks user interactions
- It is **dynamic**: stores the current state of the webpage

## Part 4: Inspecting webpages with browser tools

### Opening the Web Inspector

- Modern web browsers provide tools for inspecting the source HTML and DOM of websites
- Also tells you data sources that have been loaded by the page
- This should also be your first step when starting to scrape a page

> **Tip:**
>
> To load the Web Inspector in most modern browsers, you can simply hit the F12 button

![](imgs/web-inspector-1.png)

### The Elements tab

- Allows you to inspect the DOM directly
- The tool that will allow you to identify what data you want to scrape from a website

![](imgs/web-inspector-2.png)

> **Tip:**
>
> **Tip: Viewing an element's source code**
> 1. Right click on the element you want to view
> 2. Click on "Inspect"
> 3. The element will be highlighted in the DOM (in the Elements tab)

### The Network tab: finding data sources

The network tab tracks all of the content loaded by a website. Many modern websites that use data will "fetch" the data from an external (possibly nonpublic) data source. The Network tab will show you these sources, potentially allowing you to get the data without writing any scraping code at all.

#### The places to look
- The `Fetch/XHR` filter: all of the external XLM HTTP fetch requests, often used to load external data
- The `JS` tab: Javascript files loaded by the site, which can sometimes include data
- If you're looking for GeoJSON data, you'll want to look for `.json` files

#### Example 1: Philadelphia prisons census

[Open the example website](https://www.phila.gov/departments/philadelphia-department-of-prisons/daily-headcount-and-census/)

![](imgs/prison-census.png)

#### Example 2: WSJ measles data

[Open the example website](http://graphics.wsj.com/infectious-diseases-and-vaccines/)

![](imgs/measles.png)

#### Example 3: Philly 311

[Open the example website](https://iframe.publicstuff.com/#?client_id=242)

![](imgs/philly-311.png)

> **Tip:**
>
> When using the Network tab, you can right click on the listed entry in the left. Then, you can either select the "Open in new tab" option or the "Copy response" option. This will let you get the desired data into a new window or copied to your clipboard so you can save it to a file.

## Part 5: Guided demo — Philadelphia city health centers

Let's scrape the **Locations and hours** table on the City of Philadelphia's public [City health centers page](https://www.phila.gov/services/mental-physical-health/city-health-centers/).

This replaces the unavailable Inquirer restaurant-inspection demo. The city page includes its table in the HTML response, so we can extract it with `requests` and BeautifulSoup without running JavaScript.

Open the live page in your browser. We will collect each center's name, address, services, phone information, and hours. You only need an internet connection and the `requests`, `beautifulsoup4`, and `pandas` packages; no local data file is needed. The number of locations and their details may change over time.

### Step 1: Request the HTML

Use one GET request with a timeout, then check for HTTP errors before parsing. A browser user agent helps avoid the HTTP 403 response this site can return to default automated clients. If access is denied, stop and inspect the response rather than repeatedly retrying.

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://www.phila.gov/services/mental-physical-health/city-health-centers/"
r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=30)
r.raise_for_status()

In [2]:
r.status_code

200

### Step 2: Parse the HTML with BeautifulSoup

Create the soup from the response content. BeautifulSoup lets us select elements using the same CSS selectors we see in the browser.

In [3]:
soup = BeautifulSoup(r.content, "html.parser")

### Step 3: Inspect and select the table

On the live page, scroll to **Locations and hours**, right-click a center name, and choose **Inspect**. Move up the DOM tree to the enclosing `<table>`.

The table has the class `dcf-table`. Its column headings are in `<thead>`, while the location rows are in `<tbody>`.

- `select_one(selector)` returns the first matching element, or `None`.
- `select(selector)` returns a list of all matching elements.

See the [CSS selector notes](css-selectors.md) for more examples.

In [4]:
table = soup.select_one("table.dcf-table")
if table is None:
    raise ValueError("Health center table not found. Inspect the live page for HTML changes.")

headers = [tag.get_text(" ", strip=True) for tag in table.select("thead th")]
headers

['Name', 'Address', 'Services', 'Phone', 'Hours']

Check the headings before extracting records: an HTTP 200 response alone does not prove we downloaded the expected table.

In [5]:
expected_headers = ["Name", "Address", "Services", "Phone", "Hours"]
if headers != expected_headers:
    raise ValueError(f"Unexpected table columns: {headers}. Inspect the page before continuing.")

#### Select the first location row

`tbody > tr:nth-of-type(1)` is a **CSS selector we write**, not text that appears as an HTML tag. You will not see that exact string in the Elements tab when you inspect the page.

Read the selector one piece at a time:

| Part | Meaning |
| --- | --- |
| `tbody` | The table body, containing the location rows. |
| `>` | Look for direct children of that element. |
| `tr` | A table row. |
| `:nth-of-type(1)` | Choose the first sibling of this tag type: here, the first row. |

**Follow the structure in Inspect:**

1. On the live city page, right-click **Health Center 1** and choose **Inspect**.
2. The highlighted element may be `<strong>` or its enclosing `<td>`.
3. Move upward through its parents: `<strong>` → `<td>` → `<tr>` → `<tbody>` → `<table>`. Expand the arrows beside collapsed elements as needed.
4. Notice that `<tr>` is a direct child of `<tbody>`. That relationship is what `tbody > tr` describes.

You should see a structure like this (other cells and rows are omitted):

```html
<table class="dcf-table ...">
  <tbody>
    <tr>
      <td data-label="Name">
        <strong>Health Center 1</strong>
      </td>
      <!-- Other cells in this row -->
    </tr>
    <!-- Other location rows -->
  </tbody>
</table>
```

A browser's **Copy → Copy selector** may generate a much longer selector containing positional parts such as `:nth-child(...)`. Our shorter selector is based on the structure we inspected; it does not need to match the browser's copied selector exactly.

In the code below, `table` already refers to the health centers table. We search **within that table**, rather than across the entire webpage.

In [6]:
selector = "tbody > tr:nth-of-type(1)"
first_row = table.select_one(selector)
print(first_row.prettify())

<tr>
 <td data-label="Name">
  <strong>
   Health Center 1
  </strong>
 </td>
 <td data-label="Address">
  1930 S Broad St., Fl. 2
  <br/>
  Philadelphia, PA 19145
 </td>
 <td data-label="Services">
  Urgent care STD testing and treatment only.
  <div class="disclaimer-text">
  </div>
 </td>
 <td data-label="Phone">
  (215) 685-6570
 </td>
 <td data-label="Hours">
  <strong>
   Monday
  </strong>
  <br/>
  7:45 a.m. – 7 p.m.
  <br/>
  <strong>
   Tuesday
  </strong>
  <br/>
  7:45 a.m. – 4 p.m.
  <br/>
  <strong>
   Wednesday
  </strong>
  <br/>
  7:45 a.m. – 4 p.m.*
  <br/>
  <strong>
   Thursday
  </strong>
  <br/>
  7:45 a.m. – 4 p.m.
  <br/>
  <strong>
   Friday
  </strong>
  <br/>
  7:45 a.m. – 4 p.m.
  <br/>
  <strong>
   Saturday
  </strong>
  <br/>
  Closed
  <p class="disclaimer-text">
   <em>
    * Clinic opens at 1 p.m. on first Wednesday each month. Hours subject to change with service demand.
   </em>
  </p>
 </td>
</tr>

### Step 4: Generalize the selector to all location rows

Remove `:nth-of-type(1)` to select every row. The `>` means a direct child. Starting from `table` keeps our search inside the table we already checked, and using `tbody` excludes the heading row.

**A simpler way to select the first row:** `select_one()` already returns only the first match, so this also works:

```python
first_row = table.select_one("tbody > tr")
```

Compare the three expressions:

| Expression | Result |
| --- | --- |
| `table.select_one("tbody > tr:nth-of-type(1)")` | The first location row, selected explicitly by position. |
| `table.select_one("tbody > tr")` | The first location row, because `select_one()` returns the first match. |
| `table.select("tbody > tr")` | A list of all location rows. |

Now use `select()` to collect all rows:

In [7]:
rows = table.select("tbody > tr")
if not rows:
    raise ValueError("No health center rows found. Check the live HTML and selector.")
len(rows)

9

In [8]:
row = rows[0]

### Step 5: Extract fields from one row

Each `<td>` has a `data-label` attribute identifying its column. Attribute selectors such as `td[data-label="Name"]` are easier to read than selecting a column by its position.

#### Field 1: Center name

In [9]:
name_tag = row.select_one('td[data-label="Name"]')
name_tag.attrs

{'data-label': 'Name'}

In [10]:
name = name_tag.get_text(" ", strip=True)
name

'Health Center 1'

#### Field 2: Address

Addresses contain `<br>` line breaks. `get_text(" ", strip=True)` inserts a space between text fragments and trims whitespace, so the street and city stay separated.

In [11]:
address_tag = row.select_one('td[data-label="Address"]')
address = address_tag.get_text(" ", strip=True)
address

'1930 S Broad St., Fl. 2 Philadelphia, PA 19145'

#### Fields 3–5: Services, phone information, and hours

In [12]:
services = row.select_one('td[data-label="Services"]').get_text(" ", strip=True)
phone = row.select_one('td[data-label="Phone"]').get_text(" ", strip=True)
hours = row.select_one('td[data-label="Hours"]').get_text(" ", strip=True)
{"services": services, "phone": phone, "hours": hours}

{'services': 'Urgent care STD testing and treatment only.',
 'phone': '(215) 685-6570',
 'hours': 'Monday 7:45 a.m. – 7 p.m. Tuesday 7:45 a.m. – 4 p.m. Wednesday 7:45 a.m. – 4 p.m.* Thursday 7:45 a.m. – 4 p.m. Friday 7:45 a.m. – 4 p.m. Saturday Closed * Clinic opens at 1 p.m. on first Wednesday each month. Hours subject to change with service demand.'}

#### Nested selectors and optional elements

Some centers list a separate dental phone number; others do not. Select the `<strong>` labels **inside the Phone cell**. Searching all `<strong>` tags in the row would also collect weekday names from Hours.

`select()` returns an empty list when there are no matching labels. `select_one()` would return `None`; check for it before accessing `.text`.

In [13]:
phone_labels = row.select('td[data-label="Phone"] strong')
[label.get_text(" ", strip=True) for label in phone_labels]

[]

### Step 6: Build a DataFrame

Loop over the same downloaded rows; we do not need another web request. Check required cells so a page redesign produces a useful error rather than silently recording missing values.

In [14]:
data = []
fields = {
    "name": "Name",
    "address": "Address",
    "services": "Services",
    "phone": "Phone",
    "hours": "Hours",
}

for this_row in rows:
    record = {}
    for field, label in fields.items():
        tag = this_row.select_one(f'td[data-label="{label}"]')
        if tag is None:
            raise ValueError(f"Missing {label} cell. Inspect the live table structure.")
        record[field] = tag.get_text(" ", strip=True)
    data.append(record)

scraped_df = pd.DataFrame(data)
scraped_df

,name,address,services,phone,hours
0,Health Center 1,"1930 S Broad St., Fl. 2 Philadelphia, PA 19145",Urgent care STD testing and treatment only.,(215) 685-6570,Monday 7:45 a.m. – 7 p.m. Tuesday 7:45 a.m. – ...
1,Health Center 2,"1700 S. Broad St. Unit 201 Philadelphia, PA 19145",Primary care services,Medical (215) 685-1800 Dental (215) 685-1822,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 4:3...
2,Health Center 3,"555 S. 43rd St. Philadelphia, PA 19104",Primary care services,Medical (215) 685-7504 Dental (215) 685-7506,Monday 8 a.m. – 8 p.m. Tuesday 8 a.m. – 4:30 p...
3,Health Center 4,"4400 Haverford Ave. Philadelphia, PA 19104",Primary care services,Medical (215) 685-7601 Dental (215) 685-7605,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 8 p...
4,Health Center 5,"1900 N 20th St. Philadelphia, PA 19121",Primary care services,Medical (215) 685-2933 Dental (215) 685-2938,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 8 p...
5,Health Center 6,"301 W. Girard Ave. Philadelphia, PA 19123",Primary care services,Medical (215) 685-3803 Dental (215) 685-3816,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 4:3...
6,Mattie L. Humphrey Health Center (formerly Hea...,"131 E. Chelten Ave. Philadelphia, PA 19144",Primary care services,Medical (215) 685-5701 Dental (215) 685-5738,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 4:3...
7,Health Center 10,"2230 Cottman Ave. Philadelphia, PA 19149",Primary care services,Medical (215) 685-0639 Dental (215) 685-0639,Monday 7:30 a.m. – 4 p.m. Tuesday 7:30 a.m. – ...
8,Strawberry Mansion Health Center,"2840 West Dauphin St. Philadelphia, PA 19132",Primary care services,Medical (215) 685-2401 Dental (215) 685-2401,Monday 8 a.m. – 4:30 p.m. Tuesday 8 a.m. – 4:3...

### Step 7: Prepare the addresses for spatial analysis

Extract the five-digit ZIP code from each address. Keep it as text because ZIP codes are identifiers. We can later geocode the street addresses to map the centers.

In [15]:
scraped_df["zip_code"] = scraped_df["address"].str.extract(r"\b(\d{5})\b", expand=False)
scraped_df[["name", "address", "zip_code"]].sort_values(
    ["zip_code", "name"], ignore_index=True
)

,name,address,zip_code
0,Health Center 3,"555 S. 43rd St. Philadelphia, PA 19104",19104
1,Health Center 4,"4400 Haverford Ave. Philadelphia, PA 19104",19104
2,Health Center 5,"1900 N 20th St. Philadelphia, PA 19121",19121
3,Health Center 6,"301 W. Girard Ave. Philadelphia, PA 19123",19123
4,Strawberry Mansion Health Center,"2840 West Dauphin St. Philadelphia, PA 19132",19132
5,Mattie L. Humphrey Health Center (formerly Hea...,"131 E. Chelten Ave. Philadelphia, PA 19144",19144
6,Health Center 1,"1930 S Broad St., Fl. 2 Philadelphia, PA 19145",19145
7,Health Center 2,"1700 S. Broad St. Unit 201 Philadelphia, PA 19145",19145
8,Health Center 10,"2230 Cottman Ave. Philadelphia, PA 19149",19149

#### Discuss the results

- Why use `tbody > tr` instead of every `tr` on the page?
- How does an attribute selector differ from a class selector?
- What happens when a selector matches no elements?
- Which information is lost when we flatten phone information and hours into one string?
- What would you check if the request returned HTTP 200 but the table was missing?

The output reflects the live page at execution time. Use the source page to interpret notes about closures and appointment requirements.

## Wrap-up and next steps

We requested a live public webpage, inspected its HTML, selected repeated rows, and organized their fields in a DataFrame.

**Next time:** how to scrape dynamic content!